Skip tests where source files are missing.
This means you can run the test suite with just the files from
ld-decode-testdata.

diff --git a/try-chroma-decoder b/try-chroma-decoder
--- a/try-chroma-decoder
+++ b/try-chroma-decoder
@@ -97,6 +97,11 @@ decode () {
 		esac
 	done
 
+	if ! [ -f "$lds" ]; then
+		echo >&2 "Test skipped because source file is missing: $testname"
+		return
+	fi
+
 	if $newonly && [ -f "$outdir/$testname.avi" ]; then
 		echo >&2 "Test already done: $testname"
 		return
